CREATE TABLE IF NOT EXISTS links (
  link_id serial PRIMARY KEY,
  key VARCHAR(20) UNIQUE NOT NULL,
  url TEXT NOT NULL,
  clicks INTEGER NOT NULL DEFAULT 0,
  user_id INTEGER NOT NULL,
  expires_at TIMESTAMP,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);